sources:
  - name: spacexGQL
    handler:
      graphql:
        endpoint: https://api.spacex.land/graphql/
additionalTypeDefs: |
  extend type Subscription {
    userAdded: users
  }
  extend type Mutation {
    insert_users_and_publish(name: String!, rocket: String, twitter: String): users_mutation_response
  }
additionalResolvers:
  - type: Subscription
    field: userAdded
    pubsubTopic: userAdded
  - ./src/mutation-insert_users_and_publish.js

serve:
  exampleQuery: example-queries/*.gql
