sources:
  - name: spacexGQL
    handler:
      graphql:
        endpoint: https://api.spacex.land/graphql/

additionalTypeDefs: |
  extend type Subscription {
    usersAdded: [users]
  }

transforms:
  - resolversComposition:
      - resolver: 'Mutation.insert_users'
        composer: ./src/composition/insert_user

additionalResolvers:
  - type: Subscription
    field: usersAdded
    pubsubTopic: usersAdded

serve:
  exampleQuery: example-queries/*.gql
  cors:
    origin: '*'
